<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Repro.Minimal</RootNamespace>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Hosting" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../NServiceBus/src/NServiceBus.Core/NServiceBus.Core.csproj" />
  </ItemGroup>

</Project>
